apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  # number of concurrent suites
  concurrency: 10
  metadata:
    name: 007 Espresso Support
    tags:
      - e2e
      - draxCorp
      - theOtherJaws
    build: moonraker
espresso:
  app: ./apps/calc.apk
  testApp: ./apps/calc-success.apk
suites:
  - name: "saucyBaristaCombo"
    devices:
      - name: "Google Pixel.*"
        options:
          deviceType: PHONE
          private: false
    testOptions:
      class:
        - com.example.android.testing.androidjunitrunnersample.CalculatorAddParameterizedTest
        - com.example.android.testing.androidjunitrunnersample.CalculatorInstrumentationTest
artifacts:
  download:
    when: always
    match:
      - junit.xml
      - "*.log"
    directory: ./artifacts/
