apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  # number of concurrent suites
  concurrency: 10
  metadata:
    name: 007 Espresso Support
    tags:
      - e2e
      - draxCorp
      - theOtherJaws
    build: moonraker
espresso:
  app: storage:649fe25b-4827-4e15-a7ce-633f6e2cde81
  testApp: storage:43e0d208-5c5d-4e4b-9f60-319042e5f99b 
suites:
  - name: "saucyBaristaCombo"
    devices:
      - name: "Google Pixel.*"
        options:
          deviceType: PHONE
          private: false
    testOptions:
      class:
        - com.example.android.testing.androidjunitrunnersample.CalculatorAddParameterizedTest
        - com.example.android.testing.androidjunitrunnersample.CalculatorInstrumentationTest
artifacts:
  download:
    when: always
    match:
      - junit.xml
      - "*.log"
    directory: ./artifacts/
